jobs:
  - job: DoxygenDoc
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: |
          sudo DEBIAN_FRONTEND=noninteractive
          sudo apt-get -y update
          sudo apt-get -y install doxygen graphviz
        displayName: 'Install Pakages'

      - script: |
          doxygen Doxyfile
          cd doxygen
          tar -czvf ../docs.tar.gz ./*
        displayName: 'Generate Docs'


      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'doxygen'
          artifactType: 'pipeline'
          artifactName: 'docs'
        displayName: 'Publish Doxygen'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'docs.tar.gz'
          artifactType: 'pipeline'
          artifactName: 'docs'
        displayName: 'Publish Doxygen gzip'
